import { Medio } from '@/types/medios';

export const medios: Medio[] = [
  {
    id: 'semana',
    name: 'Semana',
    logo: 'https://www.uniminutoradio.com.co/wp-content/uploads/2020/11/4545.jpg',
    bias: 'center',
    credibility: 4.1,
    country: 'colombia',
    description: 'Revista semanal de noticias y análisis político',
    audience: '8M',
    founded: '1982',
    website: 'semana.com',
    topics: ['Política', 'Economía', 'Internacional', 'Cultura']
  },
  {
    id: 'eltiempo',
    name: 'El Tiempo',
    logo: 'https://images.ctfassets.net/n1ptkpqt763u/14Zi8Z6UBJOzmrzCfIvY1o/e2d826d8168f2a5352e6bec6a91b7ebe/ElTiempo_975x300.png',
    bias: 'center',
    credibility: 4.0,
    country: 'colombia',
    description: 'Principal periódico de Colombia',
    audience: '15M',
    founded: '1911',
    website: 'eltiempo.com',
    topics: ['Colombia', 'LATAM', 'Política', 'Deportes']
  },
  {
    id: 'rcn',
    name: 'RCN Noticias',
    logo: 'https://static.wikia.nocookie.net/logopedia/images/2/29/NoticiasRCN2020.png/revision/latest?cb=20210307141751&path-prefix=es',
    bias: 'center',
    credibility: 3.9,
    country: 'colombia',
    description: 'Canal de televisión y noticias',
    audience: '12M',
    founded: '1967',
    website: 'noticias.rcn.com.co',
    topics: ['Breaking News', 'Deportes', 'Entretenimiento', 'Nacional']
  },
  {
    id: 'caracol',
    name: 'Caracol Noticias',
    logo: 'https://www.vhv.rs/dpng/d/548-5480179_caracol-logo-tv-png-caracol-televisin-transparent-png.png',
    bias: 'center',
    credibility: 3.8,
    country: 'colombia',
    description: 'Cadena radial y televisiva de noticias',
    audience: '10M',
    founded: '1948',
    website: 'caracol.com.co',
    topics: ['Nacional', 'Internacional', 'Deportes', 'Economía']
  },
  {
    id: 'larepublica',
    name: 'La República',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/66/La_Rep%C3%BAblica_logo.jpg',
    bias: 'center',
    credibility: 4.2,
    country: 'colombia',
    description: 'Periódico especializado en economía y negocios',
    audience: '3M',
    founded: '1954',
    website: 'larepublica.co',
    topics: ['Economía', 'Negocios', 'Finanzas', 'Empresas']
  },
  {
    id: 'elespectador',
    name: 'El Espectador',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaagH7EK-X-R1bH2o_IYCsb5nrcQ0jrI_BVw&s',
    bias: 'left',
    credibility: 4.3,
    country: 'colombia',
    description: 'Periódico con enfoque investigativo y análisis',
    audience: '5M',
    founded: '1887',
    website: 'elespectador.com',
    topics: ['Investigación', 'Política', 'Justicia', 'Sociedad']
  },
  {
    id: 'lasillavacia',
    name: 'La Silla Vacía',
    logo: 'https://yt3.googleusercontent.com/7ukt2wMmlg2B8XiPQLmbwaI452NqYpIVcPwUVrsTU_53clIbprRWc4E8e27-MLwhgkuO6lOx=s900-c-k-c0x00ffffff-no-rj',
    bias: 'center',
    credibility: 4.5,
    country: 'colombia',
    description: 'Medio digital especializado en política y poder',
    audience: '2M',
    founded: '2009',
    website: 'lasillavacia.com',
    topics: ['Política', 'Poder', 'Investigación', 'Análisis']
  },
  {
    id: 'lacronica',
    name: 'La Crónica',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvBgQXVNdFdK4S2UjNnoKCeV8jjsLffUvlUQ&s',
    bias: 'center',
    credibility: 3.7,
    country: 'colombia',
    description: 'Periódico regional con cobertura nacional',
    audience: '1.5M',
    founded: '1990',
    website: 'lacronica.com',
    topics: ['Regional', 'Nacional', 'Deportes', 'Cultura']
  },
  {
    id: 'diarionacion',
    name: 'Diario La Nación',
    logo: 'https://static.wikia.nocookie.net/logopedia/images/f/ff/LANACION_20002.png/revision/latest?cb=20201124050113',
    bias: 'center',
    credibility: 3.6,
    country: 'colombia',
    description: 'Diario de circulación nacional',
    audience: '1.2M',
    founded: '1985',
    website: 'lanacion.com.co',
    topics: ['Nacional', 'Regional', 'Deportes', 'Sociedad']
  },
  {
    id: 'elmeridiano',
    name: 'El Meridiano',
    logo: 'https://i1.sndcdn.com/avatars-000138553809-cm2op6-t1080x1080.jpg',
    bias: 'center',
    credibility: 3.5,
    country: 'colombia',
    description: 'Periódico especializado en deportes',
    audience: '2.5M',
    founded: '1974',
    website: 'elmeridiano.com.co',
    topics: ['Deportes', 'Fútbol', 'Nacional', 'Internacional']
  },
  {
    id: 'eluniversal',
    name: 'El Universal',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs_qgVqIS4eOXLwTZ1fMR9rsmbd802pPZ4uw&s',
    bias: 'center',
    credibility: 3.8,
    country: 'colombia',
    description: 'Periódico de la Costa Atlántica',
    audience: '1.8M',
    founded: '1948',
    website: 'eluniversal.com.co',
    topics: ['Caribe', 'Nacional', 'Economía', 'Deportes']
  },
  {
    id: 'laopinion',
    name: 'La Opinión',
    logo: 'https://play-lh.googleusercontent.com/ULpsfeFrxUWvFMVuGjoYZ4CvIsjY8N48o87HzIOoEhBgSqYBMzuYc4AL65w7VfH2Hiw',
    bias: 'center',
    credibility: 3.7,
    country: 'colombia',
    description: 'Periódico de Norte de Santander',
    audience: '800K',
    founded: '1960',
    website: 'laopinion.com.co',
    topics: ['Regional', 'Frontera', 'Nacional', 'Sociedad']
  }
];
